#!/usr/bin/bash

# Función VPN
vpnlab() {
    # If the first argument is empty,
    if [[ -z $1 ]]; then
        # print a message and exit the function
        echo "Por favor, especifica la plataforma (htb o thm)."
        return
    fi

    # Check the value of the first argument
    case $1 in
        # If the value is "htb",
        "htb")
            # print a message and run the openvpn command with the HackTheBox configuration file
            echo "Abriendo copnexión VPN con HackTheBox..."
            sudo openvpn /[Add hackthebox .ovpn configuration file path here].
            ;;
        # If the value is "thm",
        "thm")
            # print a message and run the openvpn command with the TryHackMe configuration file
            echo "Abriendo conexión VPN con TryHackMe..."
            sudo openvpn /[ Add path to tryhackme's .ovpn configuration file here].
            ;;
        # If the value is anything else,
        *)
            # print an error message and exit the function
            echo "Plataforma no reconocida."
            return
            ;;
    esac
}
